### ISSUE TITLE
no-ip2.conf not created

### ISSUE THREAD

**Issue by dnguneratne** [hypriot/rpi-noip#3]
Step 2 (Readme) is able to pick up the hostname registered in my no-ip.com account, and I get the message "New configuration file '/usr/local/etc/no-ip2.conf' created.". However, the file is not created.

**Comment by amine250** [comment]
It's created inside the container.

/ # find . -name "no-ip2.conf"
./usr/local/etc/no-ip2.conf

**Comment by amine250** [comment]
/usr/local/etc/no-ip2.conf is created inside the container.
I create a folder in / named noip, then I launched:
`sudo docker run -ti -v "/noip:/usr/local/etc/" hypriot/rpi-noip noip2 -C`
The file is then created on the host machine in /noip:
```
/noip $ ls
no-ip2.conf
```

You can then run the container with 
`sudo docker run -d -v "/noip:/usr/local/etc/" --restart=always hypriot/rpi-noip`

**Comment by firecyberice** [comment]
You can look at the file content by executing `docker run --rm -v noip:/usr/local/etc hypriot/rpi-noip cat /usr/local/etc/no-ip2.conf`.
