### ISSUE TITLE
Error when creating config

### ISSUE THREAD

**Issue by caillou** [hypriot/rpi-noip#5]
Running the following command yields an error:

```
$ docker run \
  --name=noip \
  -ti \
  -v "/path/to/noip/config:/usr/local/etc/" \
  hypriot/rpi-noip \
  noip2 -C

standard_init_linux.go:207: exec user process caused "exec format error"
```

I am running this on `Ubuntu Server 18.10` with `Docker 18.09.3, build 774a1f4`.

**Comment by StefanScherer** [comment]
This image is for linux/arm 32bit machines like the Raspberry Pi. On other Linux machines you typically get this exec format error.

**Comment by caillou** [comment]
@StefanScherer now that makes sense ;) 

Should I open a PR with an edit of the `Readme.md` to avoid confusion for future users of the container?
